import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';
import { PoppinsVariable } from '@/lib/fonts';
import ClientProvider from '@/shared/components/layout/client-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          variables: { colorPrimary: '#4171EA' },
        }}
      >
        <body className={`${PoppinsVariable} suppressHydrationWarning antialiased`}>
          <NextTopLoader showSpinner={false} />
          <ClientProvider>{children}</ClientProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
